export type Q={q:string;options:string[];why:string;source?:string;code?:string};
export type Module={id:string;en:string;vi:string;summaryEn:string;summaryVi:string;lessonEn:string[];lessonVi:string[];source:string;questions:Q[]};
export const modules:Module[]=[
{id:'basics',en:'Retium Fundamentals',vi:'Tổng quan Retium',summaryEn:'Understand the network and its core concepts.',summaryVi:'Tìm hiểu mạng lưới và các khái niệm nền tảng.',lessonEn:['Retium is a Layer-1 blockchain built from scratch in Rust.','Its PrimeMesh design organizes blocks in a multidimensional mesh rather than a single sequential chain.','RTM is the native coin used for network fees and staking.','This independent learning website is not an official Retium product.'],lessonVi:['Retium là blockchain Layer-1 được xây dựng từ đầu bằng Rust.','PrimeMesh tổ chức các block thành mạng lưới đa chiều thay vì một chuỗi tuần tự duy nhất.','RTM là đồng coin gốc dùng cho phí mạng và staking.','Website học tập độc lập này không phải sản phẩm chính thức của Retium.'],source:'https://retium.org/understand',questions:[
{q:'What kind of blockchain is Retium?',options:['Layer 1','Layer 2 rollup','Centralized database','Bitcoin sidechain'],why:'Retium describes itself as a Layer-1 network.'},
{q:'What programming language is Retium built in?',options:['Python','Rust','Solidity','Java'],why:'Retium is built from scratch in Rust.'},
{q:'What is the native coin of the network?',options:['ETH','Pie','RTM','rUSD'],why:'RTM is the native coin of Retium.'},
{q:'Which term names Retium’s mesh architecture?',options:['PrimeMesh','RollupMesh','Sidechain','Hashgraph'],why:'Retium calls its architecture PrimeMesh.'},
{q:'Which of these is a purpose of RTM?',options:['Network fees','A guaranteed dividend','Company shares','Guaranteed profits'],why:'RTM is used for network fees and other protocol functions.'}]},
{id:'mesh',en:'PrimeMesh & Proof of Math',vi:'PrimeMesh và Proof of Math',summaryEn:'Explore mathematical block structure.',summaryVi:'Khám phá cấu trúc block dựa trên toán học.',lessonEn:['PrimeMesh uses prime-number relationships to determine block positions and connections.','A new prime is introduced at each tick.','Proof of Math determines valid block structure through deterministic mathematical rules.','Multiple open blocks can process work in parallel.'],lessonVi:['PrimeMesh sử dụng quan hệ giữa các số nguyên tố để xác định vị trí và kết nối block.','Mỗi tick đưa vào một số nguyên tố mới.','Proof of Math xác định cấu trúc block hợp lệ bằng các quy tắc toán học có tính xác định.','Nhiều open block có thể xử lý song song.'],source:'https://retium.org/understand',questions:[
{q:'What mathematical objects help organize PrimeMesh?',options:['Prime numbers','Random colors','Stock prices','Calendar dates'],why:'Prime-number relationships determine mesh positions and connections.'},
{q:'What is introduced at each tick?',options:['A new prime','A new cryptocurrency','A new wallet','A new smart contract'],why:'The architecture introduces a new prime at each tick.'},
{q:'What does PoM stand for?',options:['Proof of Mining','Proof of Math','Price of Mesh','Protocol of Minting'],why:'PoM means Proof of Math.'},
{q:'How does PrimeMesh differ from a single sequential chain?',options:['It uses multiple connected block paths','It has no blocks','It only stores NFTs','It requires a central server'],why:'PrimeMesh is multidimensional rather than a single sequential path.'},
{q:'What determines valid block structure in PoM?',options:['A social-media vote','A mining race','Deterministic mathematical rules','An exchange order book'],why:'Proof of Math uses deterministic rules for block structure.'}]},
{id:'routing',en:'Router & Open Blocks',vi:'Router và Open Blocks',summaryEn:'Follow how transactions are distributed.',summaryVi:'Theo dõi cách phân phối giao dịch.',lessonEn:['The Router assigns transactions directly to available open blocks.','Retium’s architecture does not use a traditional mempool.','Multiple open blocks can process transactions in parallel.','A transaction’s finality and its block’s finality are distinct stages.'],lessonVi:['Router phân giao dịch trực tiếp tới các open block sẵn có.','Kiến trúc Retium không sử dụng mempool truyền thống.','Nhiều open block có thể xử lý giao dịch song song.','Finality của giao dịch và finality của block là hai giai đoạn khác nhau.'],source:'https://retium.org/understand',questions:[
{q:'What routes transactions to open blocks?',options:['The Router','An NFT gallery','A price oracle','A centralized exchange'],why:'The Router assigns transactions to open blocks.'},
{q:'Does Retium use a traditional mempool?',options:['Yes, always','No','Only for NFTs','Only on weekends'],why:'Retium describes a direct-routing design without a traditional mempool.'},
{q:'How can several open blocks work?',options:['Only one at a time','Only after mainnet','In parallel','Only with an exchange'],why:'Parallel open blocks are a core part of the architecture.'},
{q:'Which finality distinction matters?',options:['Transaction vs block finality','Mobile vs desktop finality','Wallet vs browser finality','NFT vs image finality'],why:'Transaction finality and block finality are separate stages.'},
{q:'What is the Router’s primary role?',options:['Choose a profile picture','Distribute transactions','Mint every NFT','Store user passwords'],why:'The Router distributes transactions to open blocks.'}]},
{id:'validators',en:'Validator Roles',vi:'Vai trò Validator',summaryEn:'Meet Workers, Suits and Keepers.',summaryVi:'Tìm hiểu Workers, Suits và Keepers.',lessonEn:['Workers validate individual transactions.','Five Workers are assigned to a transaction; at least three approvals are required.','Keepers maintain full mesh state and independently recompute block results.','Suits coordinate block finality and communicate the finality verdict.'],lessonVi:['Workers xác thực từng giao dịch.','Năm Worker được phân cho một giao dịch; cần ít nhất ba chấp thuận.','Keepers duy trì trạng thái đầy đủ của mesh và tính toán độc lập kết quả block.','Suits phối hợp finality của block và truyền thông báo kết quả.'],source:'https://retium.org/validators',questions:[
{q:'Which role validates individual transactions?',options:['Worker','Keeper','Suit','Explorer'],why:'Workers validate individual transactions.'},
{q:'How many Workers are assigned to a transaction?',options:['2','3','5','10'],why:'Retium assigns five Workers to each transaction.'},
{q:'How many of five Worker approvals are required?',options:['1','2','At least 3','All 5'],why:'At least three of five Worker approvals are required.'},
{q:'Which role maintains full mesh state?',options:['Wallet','Keeper','NFT creator','Router UI'],why:'Keepers maintain the full mesh state.'},
{q:'Which role coordinates block finality?',options:['Suit','Worker','Faucet','Marketplace'],why:'Suits coordinate block finality.'}]},
{id:'wallet',en:'Wallet, RTM & NFTs',vi:'Ví, RTM và NFT',summaryEn:'Learn the practical wallet and NFT flows.',summaryVi:'Học các thao tác ví và NFT.',lessonEn:['The wallet supports sending and receiving RTM and viewing transaction activity.','Staking RTM mints Pie at a 1:1 ratio; unstaking burns the corresponding Pie.','NFT workflows can include creating a collection, minting, listing and transferring.','Testnet RTM is for testing and has no real-world value. Never enter a recovery phrase into a quiz website.'],lessonVi:['Ví hỗ trợ gửi, nhận RTM và xem lịch sử giao dịch.','Staking RTM tạo Pie theo tỷ lệ 1:1; unstaking đốt lượng Pie tương ứng.','Luồng NFT có thể gồm tạo bộ sưu tập, mint, list và chuyển NFT.','RTM testnet chỉ phục vụ thử nghiệm, không có giá trị thực. Không nhập recovery phrase vào website quiz.'],source:'https://retium.org/testnet',questions:[
{q:'What is Pie associated with?',options:['Validator staking','Image compression','Explorer search','A browser extension'],why:'Pie represents RTM staked in the validator system.'},
{q:'What happens to Pie on unstaking?',options:['It doubles','It is burned','It becomes an NFT','It is sent to X'],why:'The corresponding Pie is burned when RTM is unstaked.'},
{q:'What does minting an NFT mean?',options:['Creating an NFT on-chain','Deleting a wallet','Changing a browser','Signing in to Discord'],why:'Minting creates the NFT on-chain.'},
{q:'What should a quiz website request?',options:['Your recovery phrase','Your private key','Neither recovery phrase nor private key','Your wallet password'],why:'Learning websites do not need wallet secrets.'},
{q:'What is the purpose of testnet RTM?',options:['Guaranteed financial return','Network testing','Company ownership','Bank deposit'],why:'Testnet RTM is for testing and has no real-world value.'}]},
{id:'security',en:'Security & Network',vi:'Bảo mật và mạng lưới',summaryEn:'Understand signatures and verification.',summaryVi:'Tìm hiểu chữ ký và cách xác minh.',lessonEn:['Retium announced a post-quantum signature migration using ML-DSA-44.','After the migration, existing wallets display new addresses controlled by the same backed-up recovery phrase, according to Retium’s user guidance.','An Explorer helps people independently inspect blocks, transactions, addresses and contracts once available.','Check official announcements for current network availability; this course does not claim a release date.'],lessonVi:['Retium đã công bố chuyển đổi chữ ký hậu lượng tử sang ML-DSA-44.','Theo hướng dẫn của Retium, sau chuyển đổi ví hiện địa chỉ mới nhưng vẫn do recovery phrase đã sao lưu kiểm soát.','Explorer giúp kiểm tra độc lập block, giao dịch, địa chỉ và hợp đồng khi được phát hành.','Kiểm tra thông báo chính thức về tình trạng mạng; khóa học này không khẳng định ngày phát hành.'],source:'https://retium.org/',questions:[
{q:'Which post-quantum signature scheme did Retium announce?',options:['ML-DSA-44','RSA-1024','MD5','SHA-1'],why:'Retium announced a migration to ML-DSA-44.'},
{q:'After the announced wallet migration, what controls the new address?',options:['A social account','The existing backed-up recovery phrase','An NFT image','An Explorer search'],why:'Retium stated the underlying wallet secret remains the same.'},
{q:'What can a blockchain Explorer help inspect?',options:['Blocks and transactions','A user’s private key','A recovery phrase','A wallet password'],why:'Explorers expose public on-chain information, not wallet secrets.'},
{q:'Should a user share their recovery phrase to obtain a quiz certificate?',options:['Yes','Only with admins','No','Only on testnet'],why:'Never share a recovery phrase to obtain an educational certificate.'},
{q:'Where should changing network status be checked?',options:['Unverified direct messages','Official project announcements','Random screenshots only','A certificate image'],why:'Official announcements are the appropriate source for current network status.'}]}
];



