import type {Metadata} from 'next';
import {verify} from '../../../lib/certificate';
import {modules} from '../../questions';
import {headers} from 'next/headers';
import {notFound} from 'next/navigation';
import Link from 'next/link';
export const runtime='nodejs';
type Props={params:Promise<{token:string}>};
async function urlBase(){const h=await headers();const configured=process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/,'');if(configured)return configured;const host=h.get('host')||'localhost:3000';return `${host.startsWith('localhost')?'http':'https'}://${host}`}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {token}=await params;const c=verify(token);if(!c)return {title:'Certificate not found'};const mod=modules.find(m=>m.id===c.module)!;const base=await urlBase();const url=`${base}/share/${encodeURIComponent(token)}`;return {title:`${c.name} · Retium Academy Certificate`,description:`${c.name} scored ${c.score}/${c.total} in ${mod.en} · Independent community learning project`,openGraph:{title:`${c.name} · Retium Academy`,description:`${mod.en} · ${c.score}/${c.total}`,url,images:[{url:`${base}/api/og/${encodeURIComponent(token)}`,width:1200,height:630,alt:'Retium Academy knowledge certificate'}]},twitter:{card:'summary_large_image',title:`${c.name} · Retium Academy Certificate`,description:`${mod.en} · Score ${c.score}/${c.total}`,images:[`${base}/api/og/${encodeURIComponent(token)}`]}}}
export default async function Share({params}:Props){const {token}=await params;const c=verify(token);if(!c)notFound();const mod=modules.find(m=>m.id===c.module)!;const base=await urlBase();return <main style={{minHeight:'100vh',background:'#10131b',color:'#fff',fontFamily:'Arial,sans-serif',padding:'40px 16px',textAlign:'center'}}><div style={{maxWidth:850,margin:'auto',padding:30,border:'2px solid #ff5b24',borderRadius:16,background:'#1b202b'}}><img src="/retium-logo.png" alt="Retium logo" width={76} height={76}/><p style={{color:'#ff9558',letterSpacing:4}}>RETIUM ACADEMY</p><h1>Certificate of Knowledge</h1><p>This certificate is presented to</p><h2 style={{fontSize:40,overflowWrap:'anywhere'}}>{c.name}</h2><p style={{color:'#ff9558'}}>{mod.en}</p><h2>Score: {c.score} / {c.total}</h2><p>Issued {new Date(c.issued).toLocaleDateString('en-GB')} · Verified learning result</p><p style={{color:'#9ca3af',fontSize:12}}>Independent community certificate. Not an official Retium credential or on-chain NFT.</p><img style={{width:'100%',maxWidth:750,borderRadius:12}} src={`/api/og/${encodeURIComponent(token)}`} alt="Certificate image"/></div><p><Link style={{color:'#ff9558'}} href="/">← Retium Academy</Link></p></main>}
