import {NextResponse} from 'next/server';
import {modules} from '../../questions';
export const runtime='nodejs';
export const dynamic='force-dynamic';
const url=process.env.SUPABASE_URL;
const key=process.env.SUPABASE_SECRET_KEY;
function config(){if(!url||!key)throw Error('Supabase server configuration missing');return {apikey:key,Authorization:`Bearer ${key}`}}
function today(){return new Date().toISOString().slice(0,10)}
export async function GET(){try{const headers=config();const from=`${today()}T00:00:00.000Z`;const to=new Date(Date.parse(from)+86400000).toISOString();const r=await fetch(`${url}/rest/v1/quiz_results?select=points,players(x_username)&completed_at=gte.${encodeURIComponent(from)}&completed_at=lt.${encodeURIComponent(to)}&limit=10000`,{headers,cache:'no-store'});if(!r.ok)throw Error(`Database read failed (${r.status})`);const data=await r.json();const scores=new Map<string,number>();for(const item of data){const name=String(item.players?.x_username||'');if(name)scores.set(name,Math.max(scores.get(name)||0,Number(item.points)||0))}const rows=[...scores].map(([name,score])=>({name,score,day:today()})).sort((a,b)=>b.score-a.score).slice(0,100);return NextResponse.json({rows},{headers:{'Cache-Control':'no-store'}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Leaderboard unavailable'},{status:503})}}
export async function POST(req:Request){try{const headers=config();const body=await req.json();const name=String(body.name||'').replace(/^@/,'').trim().toLowerCase();const mod=modules.find(m=>m.id===body.module);const ids=body.questionIds,answers=body.answers;if(!/^[a-z0-9_]{1,15}$/.test(name)||!mod||!Array.isArray(ids)||!Array.isArray(answers)||ids.length!==5||answers.length!==5||new Set(ids).size!==5||!ids.every((v:unknown)=>Number.isInteger(v)&&Number(v)>=0&&Number(v)<mod.questions.length)||!answers.every((v:unknown)=>Number.isInteger(v)&&Number(v)>=-1&&Number(v)<=3))return NextResponse.json({error:'Invalid X username or quiz result'},{status:400});const correct=answers.filter((a:number,i:number)=>a===mod.questions[ids[i]].answer).length;const points=correct*100;const p=await fetch(`${url}/rest/v1/players`,{method:'POST',headers:{...headers,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({x_username:name})});if(!p.ok)throw Error(`Player save failed (${p.status})`);const players=await p.json();const q=await fetch(`${url}/rest/v1/quiz_results`,{method:'POST',headers:{...headers,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({player_id:players[0].id,module_id:mod.id,correct_answers:correct,points})});if(!q.ok)throw Error(`Score save failed (${q.status})`);return NextResponse.json({correct,points})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to save score'},{status:503})}}
